---
    - hosts: tag_Name_abotyan_app
      become: yes

      tasks:
        - name: Docker back. Pull image from nexus
          docker_image:
            name: "10.20.40.176:8084/backapp"
            source: pull

        - name: Docker back. Create container
          docker_container:
            name: backapp_container
            image: "10.20.40.176:8084/backapp"
            state: started
            recreate: yes
            ports:
              - "8080:8080"
            env:
              DB_USERNAME: "{{DB_USERNAME}}"
              DB_PASSWORD: "{{DB_PASSWORD}}"
              DB_URL: "{{DB_URL}}"
              DB_PORT: "{{DB_PORT}}"
              DB_NAME: "{{DB_NAME}}"
