FROM node:10-alpine as install-node

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY frontend/package*.json ./

USER node

RUN npm install

COPY --chown=node:node frontend .

RUN npm run build

FROM nginx:1.12-alpine

COPY --from=install-node /home/node/app/build /usr/share/nginx/html

COPY docker/conf /etc/nginx/conf.d/default.conf 

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
