pipeline{
    agent{
        label "slave1"
    }


    environment {
      registry = "10.20.40.176:8084"
    }

    stages{ 


        stage("Docker build images"){
            parallel{
                
                stage("Docker build Front image"){
                        steps{
                                sh '''
                                docker build -t 10.20.40.176:8084/frontapp -f docker/Dockerfile-front .
                                '''
                        }  
                }
                
                stage("Docker build Back image"){
                        steps{
                                sh '''
                                docker build -t 10.20.40.176:8084/backapp -f docker/Dockerfile-back .
                                '''  
                        }  
                }
            
            }
        }



        stage("Docker pull images to Nexus registry"){
            parallel{
                
                stage("Docker pull Front image"){
                        steps{
                            withDockerRegistry(credentialsId: 'nexus_registry', url: 'http://10.20.40.176:8084/repository/javaapp'){
                                sh '''
                                docker push 10.20.40.176:8084/frontapp
                                '''
                            }
                        }  
                }
                
                stage("Docker pull Back image"){
                        steps{
                            withDockerRegistry(credentialsId: 'nexus_registry', url: 'http://10.20.40.176:8084/repository/javaapp'){
                                sh '''
                                docker push 10.20.40.176:8084/backapp
                                '''  
                            }
                        }  
                }
            
            }
        }

    }
    
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}
