pipeline{
    agent{
        label "slave1"
    }
    stages{
        stage("Clean workspace"){
            steps{
                sh '''
                ls -la
                pwd
                cd frontend
                '''
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
    }
    
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}
