pipeline{
    agent{
        label "slave1"
    }


    environment{
      registry = "10.20.40.176:8084"
    }

    stages{ 


        stage("Docker build images"){
            parallel{
                
                stage("Docker build Front image"){
                        steps{
                                sh '''
                                docker build -t 10.20.40.176:8084/frontapp -f docker/Dockerfile-front .
                                '''
                        }  
                }
                
                stage("Docker build Back image"){
                        steps{
                                sh '''
                                docker build -t 10.20.40.176:8084/backapp -f docker/Dockerfile-back .
                                '''  
                        }  
                }
            
            }
        }



        stage("Docker push images to Nexus registry"){
            parallel{
                
                stage("Docker push Front image"){
                        steps{
                            withDockerRegistry(credentialsId: 'nexus_registry', url: 'http://10.20.40.176:8084/repository/javaapp'){
                                sh '''
                                docker push 10.20.40.176:8084/frontapp
                                '''
                            }
                        }  
                }
                
                stage("Docker push Back image"){
                        steps{
                            withDockerRegistry(credentialsId: 'nexus_registry', url: 'http://10.20.40.176:8084/repository/javaapp'){
                                sh '''
                                docker push 10.20.40.176:8084/backapp
                                '''  
                            }
                        }  
                }
            
            }
        }


        stage("Deploy images from Nexus registry to front targets"){
            steps{
                    
                    withCredentials([string(credentialsId: 'NEXUS_USER_ID', variable: 'NEXUS_USER'), 
                        string(credentialsId: 'NEXUS_PASS_ID', variable: 'NEXUS_PASS'), 
                        string(credentialsId: 'NEXUS_URL_ID', variable: 'NEXUS_URL')]) {
                        sh 'ansible-playbook -i ci/ansible/ec2.py ci/ansible/front_deploy.yaml --extra-vars "user=${NEXUS_USER} pass=${NEXUS_PASS} url=${NEXUS_URL}"'        
                    }
            }  
        }


        stage("Deploy images from Nexus registry to back targets"){
            steps{

                    withCredentials([string(credentialsId: 'NEXUS_USER_ID', variable: 'NEXUS_USER'),
                        string(credentialsId: 'NEXUS_PASS_ID', variable: 'NEXUS_PASS'),
                        string(credentialsId: 'NEXUS_URL_ID', variable: 'NEXUS_URL'),
                        string(credentialsId: 'DB_USERNAME', variable: 'DB_USERNAME'),
                        string(credentialsId: 'DB_PASSWORD', variable: 'DB_PASSWORD'),
                        string(credentialsId: 'DB_URL', variable: 'DB_URL'),
                        string(credentialsId: 'DB_PORT', variable: 'DB_PORT'),
                        string(credentialsId: 'DB_NAME', variable: 'DB_NAME')]){
                        sh 'ansible-playbook -i ci/ansible/ec2.py ci/ansible/back_deploy.yaml --extra-vars "user=${NEXUS_USER} pass=${NEXUS_PASS} url=${NEXUS_URL} db_username=${DB_USERNAME} db_password=${DB_PASSWORD} db_url=${DB_URL} db_port=${DB_PORT} db_name=${DB_NAME}"'
                    }
            }
        }



    }
    
        post{
            always{
                echo "========always========"
            }
            success{
                echo "========pipeline executed successfully ========"
            }
            failure{
                echo "========pipeline execution failed========"
            }
        }
}
